server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PerfTestSpring?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: error
